# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swipe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swipe
pod 'KMPlaceholderTextView', '~> 1.4.0'
pod 'IQKeyboardManager’
pod 'Alamofire'
pod 'Kingfisher', '~> 4.0'
pod 'GoogleMaps'
pod 'SkyFloatingLabelTextField', '~> 3.0'
pod 'TransitionButton'
pod 'IHProgressHUD'


end
