# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swipe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swipe
pod 'KMPlaceholderTextView', '~> 1.4.0'
pod 'IQKeyboardManager’
pod 'Alamofire'
pod 'Kingfisher', '~> 4.0'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'SkyFloatingLabelTextField', '~> 3.0'
pod 'TransitionButton'
#pod 'IHProgressHUD'
pod 'IHProgressHUD', :git => 'https://github.com/Swiftify-Corp/IHProgressHUD.git'
pod 'Toast-Swift', '~> 4.0.0'
pod 'SVProgressHUD'
pod 'FBSDKCoreKit', '~>4.38.0'
pod 'FBSDKLoginKit', '~>4.38.0'
pod 'FBSDKShareKit', '~>4.38.0'
pod 'GoogleSignIn'
pod 'Stripe', '~> 5.1.4'

end
